export interface CardModel
{
    card_id: String,
    foil_card_id: String,
    card_set_id: String,
    card_name: String,
    card_name_ruby: String,
    is_foil: String,
    char_type: String,
    clan: String,
    tribe_name: String,
    skill: String,
    skill_condition: String,
    skill_target: String,
    skill_option: String,
    skill_preprocess: String,
    skill_disc: String,
    org_skill_disc: String,
    evo_skill_disc: String,
    org_evo_skill_disc: String,
    cost: String,
    atk: String,
    life: String,
    evo_atk: String,
    evo_life: String,
    rarity: String,
    get_red_ether: String,
    use_red_ether: String,
    description: String,
    evo_description: String,
    cv: String,
    copyright: String,
    base_card_id: String,
    normal_card_id: String,
    format_type: String,
    restricted_count: String
}